providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = ["npm install"]
onlyIncludeFiles = ["package.json", "package-lock.json"]

[phases.build]
cmds = []

[start]
cmd = "npm start"
