[phases.setup]
nixPkgs = ["flutter"]
aptPkgs = ["curl", "wget", "unzip", "git"]

[phases.install]
cmds = ["flutter pub get"]

[phases.build]
cmds = ["flutter build web"]

[start]
cmd = "npx serve build/web -l 8080"
